window.fluidosRefrigerantes = [  {
    id: "r22",
    nome: "R22",
    familia: "HCFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Ar-condicionado e refrigeração comercial antigos",
    oleo: "Mineral / AB",
    glide: "Baixo",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "R438A, R407C e outros, conforme aplicação",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Uso em fase de eliminação e atenção ambiental",
    manuseio: "Confirmar compatibilidade do óleo e componentes no retrofit",
    notaTecnica: "Muito comum em sistemas antigos. Hoje exige atenção por restrições ambientais e substituições adequadas."
  },
  {
    id: "r134a",
    nome: "R134a",
    familia: "HFC",
    classe: "A1",
    pressao: "Baixa/Média",
    aplicacao: "Refrigeração comercial, doméstica e automotiva",
    oleo: "POE / PAG",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "R12",
    substitutoPor: "R1234yf em algumas aplicações automotivas",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Sim",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Verificar óleo correto conforme aplicação",
    manuseio: "Evitar contaminação cruzada entre óleo POE e PAG",
    notaTecnica: "Muito usado em refrigeração e linha automotiva. Pressões moderadas e serviço relativamente conhecido."
  },
  {
    id: "r404a",
    nome: "R404A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Refrigeração comercial de baixa e média temperatura",
    oleo: "POE",
    glide: "Baixo",
    tipo: "Mistura zeotrópica",
    substitui: "—",
    substitutoPor: "R448A / R449A",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Consumo energético e substituição por opções mais modernas",
    manuseio: "Em vazamento, atenção ao fracionamento em intervenções maiores",
    notaTecnica: "Fluido muito usado em refrigeração comercial. Hoje costuma ser comparado com R448A e R449A."
  },
  {
    id: "r407c",
    nome: "R407C",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Ar-condicionado e alguns retrofits de R22",
    oleo: "POE",
    glide: "Alto",
    tipo: "Mistura zeotrópica",
    substitui: "R22 em algumas aplicações",
    substitutoPor: "—",
    baixaTemp: "Limitado",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Glide mais alto exige atenção na leitura e carga",
    manuseio: "Carregar preferencialmente na fase líquida",
    notaTecnica: "Muito lembrado em retrofit de R22, mas o glide exige cuidado técnico no serviço."
  },
  {
    id: "r410a",
    nome: "R410A",
    familia: "HFC",
    classe: "A1",
    pressao: "Alta",
    aplicacao: "Ar-condicionado split, multisplit e sistemas semelhantes",
    oleo: "POE",
    glide: "Quase zero",
    tipo: "Mistura quase azeotrópica",
    substitui: "—",
    substitutoPor: "R32 em muitos projetos novos",
    baixaTemp: "Não",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Alta pressão de trabalho",
    manuseio: "Usar manifold, mangueiras e recolhedora compatíveis com alta pressão",
    notaTecnica: "Muito usado em climatização. Exige atenção especial com pressão e ferramental adequado."
  },
  {
    id: "r32",
    nome: "R32",
    familia: "HFC",
    classe: "A2L",
    pressao: "Alta",
    aplicacao: "Ar-condicionado residencial e comercial leve",
    oleo: "POE",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Não",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "Inflamabilidade leve e pressão elevada",
    manuseio: "Seguir procedimentos de segurança para A2L e garantir ventilação adequada",
    notaTecnica: "Muito presente em equipamentos mais novos. Boa eficiência, mas exige cuidado por ser A2L."
  },
  {
    id: "r438a",
    nome: "R438A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de R22 em várias aplicações",
    oleo: "Compatível com mineral, AB e POE em muitos casos",
    glide: "Médio",
    tipo: "Mistura zeotrópica",
    substitui: "R22",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Confirmar aplicação e desempenho no retrofit específico",
    manuseio: "Verificar retorno de óleo e condições reais do sistema",
    notaTecnica: "Conhecido como opção de retrofit para R22, mas deve ser avaliado caso a caso."
  },
  {
    id: "r448a",
    nome: "R448A",
    familia: "HFO/HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Refrigeração comercial de média e baixa temperatura",
    oleo: "POE",
    glide: "Alto",
    tipo: "Mistura zeotrópica",
    substitui: "R404A / R507 em várias aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Glide elevado e ajuste fino em retrofit",
    manuseio: "Avaliar válvula, regulagem e desempenho após conversão",
    notaTecnica: "Muito usado como alternativa mais moderna ao R404A em refrigeração comercial."
  },
  {
    id: "r449a",
    nome: "R449A",
    familia: "HFO/HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Refrigeração comercial de média e baixa temperatura",
    oleo: "POE",
    glide: "Alto",
    tipo: "Mistura zeotrópica",
    substitui: "R404A / R507 em várias aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Glide elevado e necessidade de avaliação do sistema",
    manuseio: "Observar superaquecimento, sub-resfriamento e regulagens após retrofit",
    notaTecnica: "Alternativa importante ao R404A, com uso frequente em refrigeração comercial."
  },
  {
    id: "r290",
    nome: "R290",
    familia: "HC",
    classe: "A3",
    pressao: "Média",
    aplicacao: "Refrigeração e climatização em aplicações específicas",
    oleo: "Mineral / AB / POE conforme projeto",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Alta",
    toxico: "Baixo",
    cuidadoPrincipal: "Alta inflamabilidade",
    manuseio: "Nunca tratar como fluido comum A1; seguir rigorosamente normas e segurança",
    notaTecnica: "Excelente desempenho em muitas aplicações, mas exige respeito total às condições de segurança por ser A3."
  },
  {
    id: "r600a",
    nome: "R600a",
    familia: "HC",
    classe: "A3",
    pressao: "Baixa",
    aplicacao: "Refrigeração doméstica e pequenos sistemas",
    oleo: "Mineral / AB",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Sim",
    comercial: "Limitado",
    industrial: "Não",
    automotivo: "Não",
    inflamavel: "Alta",
    toxico: "Baixo",
    cuidadoPrincipal: "Alta inflamabilidade mesmo com baixa carga",
    manuseio: "Evitar fontes de ignição e respeitar procedimentos próprios para HC",
    notaTecnica: "Muito comum em refrigeradores domésticos modernos. Serviço exige atenção por ser A3."
  },
  {
    id: "r717",
    nome: "R717",
    familia: "Natural",
    classe: "B2L",
    pressao: "Média",
    aplicacao: "Refrigeração industrial",
    oleo: "Óleo apropriado para sistemas com amônia",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Não",
    comercial: "Limitado",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Sim",
    cuidadoPrincipal: "Toxicidade e exigência de operação profissional",
    manuseio: "Aplicação industrial com exigência alta de segurança, projeto e treinamento",
    notaTecnica: "Muito eficiente e tradicional em refrigeração industrial, mas fora do perfil de serviço comum em climatização leve."
  }
];