window.fluidosRefrigerantes = [  {
    id: "r22",
    nome: "R22",
    familia: "HCFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Ar-condicionado e refrigeração comercial antigos",
    oleo: "Mineral / AB",
    glide: "Baixo",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "R438A, R407C e outros, conforme aplicação",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Uso em fase de eliminação e atenção ambiental",
    manuseio: "Confirmar compatibilidade do óleo e componentes no retrofit",
    notaTecnica: "Muito comum em sistemas antigos. Hoje exige atenção por restrições ambientais e substituições adequadas."
  },
  {
    id: "r134a",
    nome: "R134a",
    familia: "HFC",
    classe: "A1",
    pressao: "Baixa/Média",
    aplicacao: "Refrigeração comercial, doméstica e automotiva",
    oleo: "POE / PAG",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "R12",
    substitutoPor: "R1234yf em algumas aplicações automotivas",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Sim",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Verificar óleo correto conforme aplicação",
    manuseio: "Evitar contaminação cruzada entre óleo POE e PAG",
    notaTecnica: "Muito usado em refrigeração e linha automotiva. Pressões moderadas e serviço relativamente conhecido."
  },
  {
    id: "r404a",
    nome: "R404A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Refrigeração comercial de baixa e média temperatura",
    oleo: "POE",
    glide: "Baixo",
    tipo: "Mistura zeotrópica",
    substitui: "—",
    substitutoPor: "R448A / R449A",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Consumo energético e substituição por opções mais modernas",
    manuseio: "Em vazamento, atenção ao fracionamento em intervenções maiores",
    notaTecnica: "Fluido muito usado em refrigeração comercial. Hoje costuma ser comparado com R448A e R449A."
  },
  {
    id: "r407c",
    nome: "R407C",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Ar-condicionado e alguns retrofits de R22",
    oleo: "POE",
    glide: "Alto",
    tipo: "Mistura zeotrópica",
    substitui: "R22 em algumas aplicações",
    substitutoPor: "—",
    baixaTemp: "Limitado",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Glide mais alto exige atenção na leitura e carga",
    manuseio: "Carregar preferencialmente na fase líquida",
    notaTecnica: "Muito lembrado em retrofit de R22, mas o glide exige cuidado técnico no serviço."
  },
  {
    id: "r410a",
    nome: "R410A",
    familia: "HFC",
    classe: "A1",
    pressao: "Alta",
    aplicacao: "Ar-condicionado split, multisplit e sistemas semelhantes",
    oleo: "POE",
    glide: "Quase zero",
    tipo: "Mistura quase azeotrópica",
    substitui: "—",
    substitutoPor: "R32 em muitos projetos novos",
    baixaTemp: "Não",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Alta pressão de trabalho",
    manuseio: "Usar manifold, mangueiras e recolhedora compatíveis com alta pressão",
    notaTecnica: "Muito usado em climatização. Exige atenção especial com pressão e ferramental adequado."
  },
  {
    id: "r32",
    nome: "R32",
    familia: "HFC",
    classe: "A2L",
    pressao: "Alta",
    aplicacao: "Ar-condicionado residencial e comercial leve",
    oleo: "POE",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Não",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "Inflamabilidade leve e pressão elevada",
    manuseio: "Seguir procedimentos de segurança para A2L e garantir ventilação adequada",
    notaTecnica: "Muito presente em equipamentos mais novos. Boa eficiência, mas exige cuidado por ser A2L."
  },
  {
    id: "r438a",
    nome: "R438A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de R22 em várias aplicações",
    oleo: "Compatível com mineral, AB e POE em muitos casos",
    glide: "Médio",
    tipo: "Mistura zeotrópica",
    substitui: "R22",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Confirmar aplicação e desempenho no retrofit específico",
    manuseio: "Verificar retorno de óleo e condições reais do sistema",
    notaTecnica: "Conhecido como opção de retrofit para R22, mas deve ser avaliado caso a caso."
  },
  {
    id: "r448a",
    nome: "R448A",
    familia: "HFO/HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Refrigeração comercial de média e baixa temperatura",
    oleo: "POE",
    glide: "Alto",
    tipo: "Mistura zeotrópica",
    substitui: "R404A / R507 em várias aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Glide elevado e ajuste fino em retrofit",
    manuseio: "Avaliar válvula, regulagem e desempenho após conversão",
    notaTecnica: "Muito usado como alternativa mais moderna ao R404A em refrigeração comercial."
  },
  {
    id: "r449a",
    nome: "R449A",
    familia: "HFO/HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Refrigeração comercial de média e baixa temperatura",
    oleo: "POE",
    glide: "Alto",
    tipo: "Mistura zeotrópica",
    substitui: "R404A / R507 em várias aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Glide elevado e necessidade de avaliação do sistema",
    manuseio: "Observar superaquecimento, sub-resfriamento e regulagens após retrofit",
    notaTecnica: "Alternativa importante ao R404A, com uso frequente em refrigeração comercial."
  },
  {
    id: "r290",
    nome: "R290",
    familia: "HC",
    classe: "A3",
    pressao: "Média",
    aplicacao: "Refrigeração e climatização em aplicações específicas",
    oleo: "Mineral / AB / POE conforme projeto",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Alta",
    toxico: "Baixo",
    cuidadoPrincipal: "Alta inflamabilidade",
    manuseio: "Nunca tratar como fluido comum A1; seguir rigorosamente normas e segurança",
    notaTecnica: "Excelente desempenho em muitas aplicações, mas exige respeito total às condições de segurança por ser A3."
  },
  {
    id: "r600a",
    nome: "R600a",
    familia: "HC",
    classe: "A3",
    pressao: "Baixa",
    aplicacao: "Refrigeração doméstica e pequenos sistemas",
    oleo: "Mineral / AB",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Sim",
    comercial: "Limitado",
    industrial: "Não",
    automotivo: "Não",
    inflamavel: "Alta",
    toxico: "Baixo",
    cuidadoPrincipal: "Alta inflamabilidade mesmo com baixa carga",
    manuseio: "Evitar fontes de ignição e respeitar procedimentos próprios para HC",
    notaTecnica: "Muito comum em refrigeradores domésticos modernos. Serviço exige atenção por ser A3."
  },
    {
    id: "r717",
    nome: "R717",
    familia: "Natural",
    classe: "B2L",
    pressao: "Média",
    aplicacao: "Refrigeração industrial",
    oleo: "Óleo apropriado para sistemas com amônia",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Não",
    comercial: "Limitado",
    industrial: "Sim",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Sim",
    cuidadoPrincipal: "Toxicidade e exigência de operação profissional",
    manuseio: "Aplicação industrial com exigência alta de segurança, projeto e treinamento",
    notaTecnica: "Muito eficiente e tradicional em refrigeração industrial, mas fora do perfil de serviço comum em climatização leve."
  },
  {
    id: "r141b",
    nome: "R141b",
    familia: "HCFC",
    classe: "A1",
    pressao: "Baixa",
    aplicacao: "Usos antigos, nichados e algumas aplicações técnicas específicas",
    oleo: "Mineral / AB",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "Aplicações variam conforme o projeto",
    baixaTemp: "Limitado",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Não",
    comercial: "Limitado",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Fluido antigo e com uso cada vez mais restrito",
    manuseio: "Confirmar finalidade real da aplicação e compatibilidade do sistema antes de qualquer intervenção",
    notaTecnica: "Não é fluido de campo comum no RAC leve atual, mas pode aparecer em contextos mais antigos ou específicos."
  },
  {
    id: "r1234yf",
    nome: "R1234yf",
    familia: "HFO",
    classe: "A2L",
    pressao: "Baixa/Média",
    aplicacao: "Ar-condicionado automotivo e aplicações mais novas de baixo GWP",
    oleo: "PAG / POE conforme aplicação",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "R134a em várias aplicações automotivas",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Limitado",
    industrial: "Não",
    automotivo: "Sim",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "Inflamabilidade leve e exigência de procedimento correto de serviço",
    manuseio: "Usar equipamento compatível e evitar práticas antigas de oficina sem controle adequado",
    notaTecnica: "Muito relevante na linha automotiva moderna. O técnico precisa respeitar o fato de ser A2L."
  },
  {
    id: "r1234ze",
    nome: "R1234ze",
    familia: "HFO",
    classe: "A2L",
    pressao: "Baixa/Média",
    aplicacao: "Sistemas específicos de refrigeração e climatização com foco em baixo GWP",
    oleo: "POE",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "Varia conforme aplicação",
    substitutoPor: "—",
    baixaTemp: "Limitado",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "A2L exige atenção ao procedimento e ao ambiente de trabalho",
    manuseio: "Confirmar compatibilidade do equipamento, ventilação e ferramental adequado",
    notaTecnica: "Fluido mais moderno e menos comum no serviço cotidiano, mas importante para o app ficar atualizado."
  },
  {
    id: "r744",
    nome: "R744",
    familia: "Natural",
    classe: "A1",
    pressao: "Muito Alta",
    aplicacao: "Sistemas transcríticos, refrigeração comercial e aplicações específicas",
    oleo: "Óleo específico conforme projeto",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Sim",
    automotivo: "Limitado",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Pressões muito elevadas e exigência técnica maior",
    manuseio: "Nunca tratar como sistema comum; usar componentes, instrumentos e procedimento próprios para CO2",
    notaTecnica: "O R744 é extremamente importante tecnicamente, mas exige outro nível de atenção por trabalhar com pressões bem altas."
  },
  {
    id: "r11",
    nome: "R11",
    familia: "CFC",
    classe: "A1",
    pressao: "Baixa",
    aplicacao: "Sistemas muito antigos e referências históricas",
    oleo: "Mineral",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "Obsoleto",
    baixaTemp: "Não",
    mediaTemp: "Limitado",
    altaTemp: "Sim",
    residencial: "Não",
    comercial: "Não",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Fluido antigo, obsoleto e associado a sistemas fora do padrão atual",
    manuseio: "Intervir apenas com critério técnico e foco em identificação, recuperação e avaliação do sistema",
    notaTecnica: "Mais útil como referência técnica e histórica do que como fluido de campo atual."
  },
  {
    id: "r12",
    nome: "R12",
    familia: "CFC",
    classe: "A1",
    pressao: "Baixa/Média",
    aplicacao: "Sistemas antigos de refrigeração e automotivos antigos",
    oleo: "Mineral",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "Diversos retrofits conforme aplicação",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Limitado",
    industrial: "Não",
    automotivo: "Limitado",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Obsolescência e necessidade de abordagem de retrofit ou preservação",
    manuseio: "Antes de qualquer carga ou serviço, confirmar histórico do sistema e viabilidade real da intervenção",
    notaTecnica: "Muito conhecido historicamente, mas fora do padrão moderno de trabalho."
  },
  {
    id: "r13",
    nome: "R13",
    familia: "CFC",
    classe: "A1",
    pressao: "Alta",
    aplicacao: "Baixíssimas temperaturas e usos especiais antigos",
    oleo: "Óleo compatível conforme projeto",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "Aplicações especiais",
    baixaTemp: "Sim",
    mediaTemp: "Não",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Não",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Fluido de nicho e fora do uso comum do técnico generalista",
    manuseio: "Só faz sentido em contexto técnico específico e com pleno entendimento do sistema",
    notaTecnica: "Importante para completar a base do app, mas pouco provável no campo comum."
  },
  {
    id: "r14",
    nome: "R14",
    familia: "CFC",
    classe: "A1",
    pressao: "Muito Alta",
    aplicacao: "Baixíssimas temperaturas e aplicações extremamente específicas",
    oleo: "Óleo específico conforme projeto",
    glide: "Zero",
    tipo: "Substância pura",
    substitui: "—",
    substitutoPor: "Aplicações especiais",
    baixaTemp: "Sim",
    mediaTemp: "Não",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Não",
    industrial: "Muito limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Pressão elevada e aplicação muito fora do RAC cotidiano",
    manuseio: "Tratar como fluido técnico de nicho, não como item de rotina",
    notaTecnica: "Entra mais por robustez de base do que por frequência real de atendimento."
  },
  {
    id: "r401a",
    nome: "R401A",
    familia: "HCFC/HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de sistemas antigos",
    oleo: "Mineral / AB / adaptação conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R12 em algumas aplicações",
    substitutoPor: "Opções variam conforme projeto",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Blend com glide e necessidade de critério em retrofit",
    manuseio: "Avaliar válvula, óleo, trocadores e condição geral antes de tratar como substituição simples",
    notaTecnica: "Mais ligado a retrofit do que a instalação nova."
  },
  {
    id: "r402a",
    nome: "R402A",
    familia: "HCFC/HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Baixa temperatura e retrofit",
    oleo: "Mineral / AB / adaptação conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R502 em algumas aplicações",
    substitutoPor: "Opções mais modernas variam conforme sistema",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Blend de retrofit que pede atenção especial ao regime de baixa temperatura",
    manuseio: "Trabalhar com carga em fase líquida e revisar compatibilidade antes de intervenção",
    notaTecnica: "Pode aparecer em sistemas convertidos e exige leitura cuidadosa do histórico."
  },
  {
    id: "r402b",
    nome: "R402B",
    familia: "HCFC/HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Baixa temperatura e retrofit",
    oleo: "Mineral / AB / adaptação conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R502 em algumas aplicações",
    substitutoPor: "Alternativas variam conforme o sistema",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Retrofit exige conferência de desempenho e retorno de óleo",
    manuseio: "Não assumir equivalência direta sem avaliar o comportamento real do sistema",
    notaTecnica: "Prático para a base da régua por aparecer em históricos de conversão."
  },
  {
    id: "r408a",
    nome: "R408A",
    familia: "HCFC/HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Retrofit de baixa e média temperatura",
    oleo: "Mineral / AB / adaptação conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R502 em algumas situações",
    substitutoPor: "Alternativas mais modernas conforme projeto",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Não",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Blend de retrofit não deve ser tratado como troca simples",
    manuseio: "Confirmar histórico do sistema, controle de expansão e carga em fase líquida",
    notaTecnica: "Importante em bases de consulta por causa de equipamentos convertidos."
  },
  {
    id: "r407a",
    nome: "R407A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Baixa e média temperatura, retrofit e substituições específicas",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R404A / R22 em algumas situações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Glide e comportamento de blend exigem procedimento correto",
    manuseio: "Carregar em fase líquida e conferir aplicação antes de usar como substituto",
    notaTecnica: "Fluido útil para retrofit e consulta prática no campo."
  },
  {
    id: "r407f",
    nome: "R407F",
    familia: "HFC",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Substituição de R404A e aplicações de refrigeração comercial",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R404A em várias aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Blend com glide e necessidade de ajuste fino conforme sistema",
    manuseio: "Monitorar superaquecimento, sub-resfriamento e resposta do equipamento após retrofit",
    notaTecnica: "Bem relevante para cenários de substituição de R404A."
  },
  {
    id: "r422d",
    nome: "R422D",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de sistemas de R22",
    oleo: "Mineral / AB / POE conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 em diversas aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Substituição de R22 deve ser tratada com critério técnico, não no automático",
    manuseio: "Verificar óleo, componentes, ajuste de carga e comportamento do sistema convertido",
    notaTecnica: "Muito útil para o técnico que lida com parque instalado antigo."
  },
  {
    id: "r427a",
    nome: "R427A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de sistemas com R22",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 em várias aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Necessita atenção à conversão e à lubrificação",
    manuseio: "Evitar tratar retrofit como simples recarga; revisar o conjunto do sistema",
    notaTecnica: "Entrou bem na base por ser ligado a substituições de R22."
  },
  {
    id: "r421a",
    nome: "R421A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de R22 e aplicações similares",
    oleo: "Mineral / AB / compatibilidade conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 em algumas aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Avaliar comportamento do sistema convertido antes de cravar equivalência",
    manuseio: "Observar retorno de óleo, expansão e rendimento após intervenção",
    notaTecnica: "Mais um nome útil para base prática de retrofit."
  },
  {
    id: "r421b",
    nome: "R421B",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit e substituições específicas de sistemas antigos",
    oleo: "Mineral / AB / compatibilidade conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 em algumas situações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Blend de retrofit requer análise do conjunto, não só da pressão",
    manuseio: "Conferir aplicação real, condição do compressor e controle de expansão",
    notaTecnica: "Útil como item de consulta avançada do app."
  },
  {
    id: "r422a",
    nome: "R422A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de sistemas antigos",
    oleo: "Mineral / AB / POE conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 / R502 em alguns casos",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Conversões pedem conferência fina do desempenho",
    manuseio: "Não confiar só em pressão; cruzar com temperatura e condição real do sistema",
    notaTecnica: "Ajuda a cobrir uma família de blends de substituição."
  },
  {
    id: "r422b",
    nome: "R422B",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit e substituições específicas",
    oleo: "Mineral / AB / POE conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 / R502 em algumas aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Misturas retrofit exigem leitura correta do glide",
    manuseio: "Carregar em líquido e acompanhar comportamento real após ajuste",
    notaTecnica: "Boa para completar a linha dos blends de retrofit."
  },
  {
    id: "r424a",
    nome: "R424A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de sistemas antigos, especialmente linha R22",
    oleo: "Mineral / AB / POE conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 em aplicações específicas",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Exige avaliação do sistema convertido e não só troca de gás",
    manuseio: "Verificar lubrificação, vazão e ajuste de expansão",
    notaTecnica: "Mais um fluido de retrofit útil na prática de campo."
  },
  {
    id: "r434a",
    nome: "R434A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Substituição e retrofit em aplicações específicas",
    oleo: "POE / conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R22 em algumas situações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Blend menos comum, mas requer a mesma disciplina técnica dos demais",
    manuseio: "Confirmar documentação do equipamento e contexto da conversão",
    notaTecnica: "Importante para uma régua mais completa."
  },
  {
    id: "r437a",
    nome: "R437A",
    familia: "HFC",
    classe: "A1",
    pressao: "Média",
    aplicacao: "Retrofit de sistemas com R12 e R22 em alguns cenários",
    oleo: "Mineral / AB / POE conforme sistema",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R12 / R22 em aplicações específicas",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Substituição depende muito da configuração original do sistema",
    manuseio: "Avaliar sempre o conjunto antes de assumir compatibilidade total",
    notaTecnica: "Útil pela variedade de contextos de retrofit em que pode aparecer."
  },
  {
    id: "r452a",
    nome: "R452A",
    familia: "HFC/HFO",
    classe: "A1",
    pressao: "Média/Alta",
    aplicacao: "Baixa e média temperatura, transporte refrigerado e substituições de R404A/R507",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R404A / R507 em várias aplicações",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Não",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Não",
    toxico: "Baixo",
    cuidadoPrincipal: "Blend moderno, mas ainda exige leitura correta de glide e ajuste",
    manuseio: "Trabalhar com carga em líquido e conferir resposta térmica do sistema",
    notaTecnica: "Bem relevante em cenários de substituição de R404A/R507."
  },
  {
    id: "r452b",
    nome: "R452B",
    familia: "HFC/HFO",
    classe: "A2L",
    pressao: "Alta",
    aplicacao: "Climatização e aplicações mais novas com foco em menor GWP",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R410A em algumas aplicações",
    substitutoPor: "—",
    baixaTemp: "Não",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "É A2L e trabalha em faixa alta de pressão",
    manuseio: "Exige ferramentas, ventilação e procedimento compatíveis com fluidos A2L",
    notaTecnica: "Importante na transição para alternativas ao R410A."
  },
  {
    id: "r454a",
    nome: "R454A",
    familia: "HFO/HFC",
    classe: "A2L",
    pressao: "Média/Alta",
    aplicacao: "Refrigeração e climatização com proposta de baixo GWP",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "Varia conforme aplicação",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "A2L exige respeito ao ambiente, ventilação e ferramental adequado",
    manuseio: "Nunca tratar como A1 comum; seguir procedimento para levemente inflamáveis",
    notaTecnica: "Entra pela importância da família de fluidos mais novos."
  },
  {
    id: "r454b",
    nome: "R454B",
    familia: "HFO/HFC",
    classe: "A2L",
    pressao: "Alta",
    aplicacao: "Climatização moderna e substituições ligadas à linha do R410A",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "R410A em várias propostas mais novas",
    substitutoPor: "—",
    baixaTemp: "Não",
    mediaTemp: "Sim",
    altaTemp: "Sim",
    residencial: "Sim",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "Alta pressão + classificação A2L",
    manuseio: "Exige prática correta de A2L e instrumentos compatíveis com a faixa de pressão",
    notaTecnica: "Um dos nomes importantes na transição da climatização moderna."
  },
  {
    id: "r454c",
    nome: "R454C",
    familia: "HFO/HFC",
    classe: "A2L",
    pressao: "Média/Alta",
    aplicacao: "Aplicações específicas de baixo GWP em refrigeração e climatização",
    oleo: "POE",
    glide: "Sim",
    tipo: "Blend",
    substitui: "Varia conforme aplicação",
    substitutoPor: "—",
    baixaTemp: "Sim",
    mediaTemp: "Sim",
    altaTemp: "Limitado",
    residencial: "Limitado",
    comercial: "Sim",
    industrial: "Limitado",
    automotivo: "Não",
    inflamavel: "Leve",
    toxico: "Baixo",
    cuidadoPrincipal: "Mesmo sendo mais novo, continua exigindo disciplina de A2L",
    manuseio: "Verificar compatibilidade do projeto, segurança e procedimento antes de atuar",
    notaTecnica: "Fecha bem a família dos fluidos mais novos na régua."
  }
];